### ISSUE TITLE
Header size too big

### ISSUE THREAD

**Issue by dktiron** [surroundaustralia/Prez#125]
Our websites are accessible via shared proxies (VMWare NSX and Nginx)
The header's size for Prez (>6kb) is greater than the default proxies buffer size (~4Kb)

![big-header](https://user-images.githubusercontent.com/110969220/183856632-4ff69e8c-d76a-4b79-85da-752f6dec5bac.png)

So if we want Prez to be accessible, we are obliged to modify this parameter for all our sites !!! (memory impact on our equipment and specific configuration)

Is it possible to decrease the header size to reach the "standard" of 4Kb ?

**Comment by nicholascar** [comment]
Hmmm... that is an interesting issue!

@dktiron thanks for bringing this issue up, though I'm not sure how easy it's going to be to address!

The reason the headers are so big is that the server is responding with available a list of alternate profiles and formats available for the resource you are looking at, as per the ConnegP standard (see https://w3c.github.io/dx-connegp/connegp/#http-listprofiles).

I've not really considered a header total size in bytes before and I'm not sure how to reduce it since it's auto-generated and following the specification.

First I'll check how large the largest headers are (are they a little over 6kb or a lot?) and then think about what to do...

**Comment by recalcitrantsupplant** [comment]
More generally we could try moving to HTTP2 via https://gitlab.com/pgjones/hypercorn which I think supports HPACK  https://httpwg.org/specs/rfc7541.html

**Comment by dktiron** [comment]
After googling and digging in RFC, I have found in the RFC 9110 : 

https://www.rfc-editor.org/rfc/rfc9110#name-field-limits
"HTTP does not place a predefined limit on the length (...) of a header" 

and https://www.rfc-editor.org/rfc/rfc9110#name-length-requirements

"HTTP does not have specific length limitations for many of its protocol elements because the lengths that might be appropriate will vary widely, depending on the deployment context and purpose of the implementation. Hence, interoperability between senders and recipients depends on shared expectations regarding what is a reasonable length for each protocol element"

The size of the protocol elements must be reasonable :-)

**Comment by dktiron** [comment]
In summary some defaults buffer size :
  Apache 2.4 : 8K
  Nginx 1.22 : 4K
  IIS: 8K to 16K (due to SPNEGO)

So I have to convince the Infrastructure Guys to modify our default  configuration

Issue can be closed

**Comment by recalcitrantsupplant** [comment]
No worries - thanks for the information
